name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jobiniah/runpod-smaug:$(date +%s) --build-arg MODEL_NAME="abacusai/Smaug-Llama-3-70B-Instruct-32K" --build-arg BASE_PATH="/models"
